# Generated by Django 5.2.4 on 2026-01-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasayana', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('specialist', models.CharField(choices=[('Chief Physician', 'DR. V MADHAVACHANDRAN'), ('Consulting Physician', 'DR. JINTU JOSE'), ('General', 'General Consultation')], max_length=50)),
                ('preferred_date', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('concerns', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
